languageCode = "en-ja"
title = "群馬大学電子計算機研究会 IGGG"
baseURL = "http://localhost:1313/"
theme = "dopetrope"

[params]
  AuthorName = "iggg.org"
  GitHubUser = "IGGG"
  Subtitle = "Information technology researching society of the Gunmer, by the Gunmer, for the Gunmer"

[params.portfolio]
    title = "My Portfolio"
    foldername = "portfolio"
    findoutmoretext = "Find out more"

[params.blog]
    title = "The Blog"
    viewalltext = "View All"
    foldername = "blog"

[params.settings]
    googleanalytics = "UA-113904582-1"
    disqus = "hugo-dopetrope"
